import { Suspense } from "react";

import { getGamesToday, getPredictionsToday } from "@/lib/api/client";
import type { Game, Prediction } from "@/lib/api/types";
import { dateLabel } from "@/lib/format";
import { GameCard } from "@/components/games/game-card";
import { Skeleton } from "@/components/ui/atoms";

export const dynamic = "force-dynamic";
export const revalidate = 60;

export const metadata = {
  title: "Today's Slate",
};

async function TodaysSlate() {
  // Fetch games + predictions in parallel — the predictions endpoint already
  // resolves missing predictions on demand server-side, so we just zip them.
  const [games, predictions] = await Promise.all([
    getGamesToday(),
    getPredictionsToday(),
  ]);

  const safeGames: Game[] = games ?? [];
  const safePreds: Prediction[] = predictions ?? [];
  const predByGame = new Map<number, Prediction>(
    safePreds.map((p) => [p.game_id, p]),
  );

  // Sort by first pitch — earliest first.
  const sorted = [...safeGames].sort(
    (a, b) =>
      new Date(a.game_datetime).getTime() - new Date(b.game_datetime).getTime(),
  );

  if (sorted.length === 0) {
    return (
      <div className="rounded-md border border-dashed border-border/80 p-10 text-center">
        <p className="font-display text-lg">No games on the slate.</p>
        <p className="mt-1 text-sm text-muted-foreground">
          The schedule may not be ingested yet, or it&apos;s an off-day. Check
          back later.
        </p>
      </div>
    );
  }

  return (
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
      {sorted.map((g) => (
        <GameCard
          key={g.game_id}
          game={g}
          prediction={predByGame.get(g.game_id) ?? null}
        />
      ))}
    </div>
  );
}

export default function GamesTodayPage() {
  return (
    <div className="container py-10">
      <header className="mb-8 flex items-end justify-between gap-4">
        <div>
          <span className="label">{dateLabel(new Date())}</span>
          <h1 className="font-display text-4xl font-semibold tracking-tight md:text-5xl">
            Today&apos;s Slate
          </h1>
          <p className="mt-2 max-w-prose text-muted-foreground">
            Win probabilities are generated by a calibrated 10-factor model
            with 10 000-iteration Monte Carlo. Tap a game for the full breakdown.
          </p>
        </div>
      </header>

      <div className="rule mb-8" />

      <Suspense fallback={<SlateSkeleton />}>
        <TodaysSlate />
      </Suspense>
    </div>
  );
}

function SlateSkeleton() {
  return (
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
      {Array.from({ length: 6 }).map((_, i) => (
        <Skeleton key={i} className="h-44" />
      ))}
    </div>
  );
}
